version: '3'
services:
  api-service:
    image: node:14
    container_name: auth_api
    volumes:
      - ./server:/server
      - ./shared:/shared
      - ./tsconfig.json:/tsconfig.json
    ports:
      - '3001:3000'
    working_dir: /server
    command: yarn run ts-node-dev --project tsconfig.json -r tsconfig-paths/register index.ts
    env_file: .env.development

  realtime-service:
    image: node:14
    container_name: auth_realtime
    volumes:
      - ./realtime:/realtime
      - ./shared:/shared
      - ./tsconfig.json:/tsconfig.json
    ports:
      - '3002:3000'
    working_dir: /realtime
    command: yarn run ts-node-dev --project tsconfig.json -r tsconfig-paths/register index.ts
    env_file: .env.development

  mongodb:
    image: mongo:5
    container_name: auth_mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: change_me
